## Trabajando con Pandas - Inicial

Pandas provee de tres datastructures principales: Series, DataFrame, e Index.
También usaremos numpy que provee una librería para manejar arrays n-dimensionales.

--------------------

# Importamos liberías comunes 

In [1]:
import numpy as np
import pandas as pd
import datetime

---------------

# Leyendo datos con Numpy


In [2]:
filename = 'data/example_data.csv'
data = np.genfromtxt(filename, delimiter=';', names=True, dtype=None, encoding='UTF')

In [3]:
data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [4]:
data.shape # dimensiones del array , se trata de un array de  5 tuplas

(5,)

In [5]:
data.dtype #tipos de datos de cada elemento de la tupla

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [6]:
%%timeit ## realiza 7 ejecuciones de 100000 loops y calcula la media y el desvio estandard
max([row[3] for row in data])

2.73 µs ± 61.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Pasamos los datos a un diccionario cuyas keys sean los nombres de las columnas y sus valores, arreglos de numpy

**data.dtype.names** Accedemos a los nombres de las columnas

Podemos iterar por los row del numpy array con **for row in data** similar a como hacemos con una lista


In [7]:

array_dict = {}

for col_index, colname in enumerate(data.dtype.names):
    array_dict[colname] = np.array([row[col_index] for row in data])
    
array_dict    

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [8]:
array_dict
array_dict['mag'].max()

6.7

Es mucho más rápido que la implementación anterior pero construir el diccionario también consume tiempo.

In [9]:
# Buscamos obtener el row del valor máximo de mag usando el subindice del máximo
np.array([value[array_dict['mag'].argmax()] for key,value in array_dict.items()])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U31')

----------------


## Series en Pandas

Es una estructura para arrays de un único tipo de dato. Es unidimensional, podría representar una columna. Los números a la izquierda representan los indices

In [10]:
place = pd.Series(array_dict['place'], name='place') #lo crea a partir de un numpy array
place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

Los atributos de la series son:
* **name** : nombre del objeto serie
* **dtype**: el tipo de datos
* **shape**: la dimensión dada por el número de filas
* **index**: retorna el objeto Index de la serie
* **values**: los valores como un numpy array

In [11]:
place.values

array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
       '42km WNW of Sola, Vanuatu',
       '13km E of Nueva Concepcion, Guatemala',
       '128km SE of Kimbe, Papua New Guinea'], dtype=object)

In [12]:
place.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
place.shape

(5,)

# Index

Index son las etiquetas del row. Puede ser un número, una fecha o un string.
Atributos:
* **name** : nombre
* **dtype** : tipo de datos del indice
* **shape**: dimensiones del indice
* **value**: los datos del objeto indice como numpy array
* **is_unique**: checkea si el indice tiene todos valores únicos

Documentación:  https:/​/​pandas.​pydata.​org/​pandas-​docs/stable/​generated/​pandas.​Index.​html.


In [14]:
print(place.index.name)

None


In [15]:
place.index.name = "Números"
print(place.index.name)

Números


In [16]:
place

Números
0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

In [17]:
place.index.values

array([0, 1, 2, 3, 4])

In [18]:
# En series como numpy se pueden usar operaciones aritméticas

print(np.array([1,2,3])+np.array([-1,-2,-3]))
print(pd.Series(np.array([1,2,3]))+pd.Series(np.array([-1,-2,-3])))

[0 0 0]
0    0
1    0
2    0
dtype: int64


Linspace crea un arreglo de numeros en numpy. Por defecto son 20 numeros y van desde inicio a fin
https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

In [19]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.linspace(0,9, num=10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
# Cuando sumamos con Series podemos perder datos dado que suma index wise.

pd.Series(np.linspace(0,4,num=5))+pd.Series(np.ones(5), index=pd.Index([1,2,3,4,5]))

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64

In [22]:
# Cuando sumamos con Series podemos perder datos dado que suma index wise.
# IMPORTANTE: Notar que perdemos información donde no puede sumar
pd.Series(np.ones(5))+pd.Series(np.ones(5), index=pd.Index([1,3,5,7,9]))

0    NaN
1    2.0
2    NaN
3    2.0
4    NaN
5    NaN
7    NaN
9    NaN
dtype: float64

# DataFrame

El DataFrame se forma a patir de Series y contiene todas las columnas de datos. Notar que también tiene indice.
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html


In [23]:
# creamos un dataframe desde un diccionario de numpy arrays
df = pd.DataFrame(array_dict)
df

time                                  place magType  \
0  2018-10-13 11:10:23.560        262km NW of Ozernovskiy, Russia     mww   
1  2018-10-13 04:34:15.580            25km E of Bitung, Indonesia     mww   
2  2018-10-13 00:13:46.220              42km WNW of Sola, Vanuatu     mww   
3  2018-10-12 21:09:49.240  13km E of Nueva Concepcion, Guatemala     mww   
4  2018-10-12 02:52:03.620    128km SE of Kimbe, Papua New Guinea     mww   

   mag  alert  tsunami  
0  6.7  green        1  
1  5.2  green        0  
2  5.7  green        0  
3  5.7  green        0  
4  5.6  green        1

In [24]:
# Para ver los docstrings
# help()
# pd.read_csv? #Ipython help
# pd.read_csv??

_Para garantizar que el resultado sea reproducible, estableceremos la semilla aquí. La semilla da un
punto de partida para la generación de números pseudoaleatorios. Sin algoritmos para
generación de números aleatorios son verdaderamente aleatorios, son deterministas y, por lo tanto,
al establecer este punto de partida, los números generados serán los mismos cada vez que el
se ejecuta el código. Libro: Data Analysis with Pandas, 2019_

In [25]:
np.random.seed(0)
pd.Series(np.random.rand(5), name='random')

0    0.548814
1    0.715189
2    0.602763
3    0.544883
4    0.423655
Name: random, dtype: float64

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.random.normal(size=(4,))


array([-0.84272405,  1.96992445,  1.26611853, -0.50587654])

In [30]:
np.random.uniform(size=10)

array([0.52889492, 0.56804456, 0.92559664, 0.07103606, 0.0871293 ,
       0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834])

Podemos usar **to_frame()** para convertir una Serie en un DataFrame

In [31]:
np.random.seed(0)
df = pd.Series(np.random.uniform(size=10)).to_frame()
df

0
0  0.548814
1  0.715189
2  0.602763
3  0.544883
4  0.423655
5  0.645894
6  0.437587
7  0.891773
8  0.963663
9  0.383442

In [32]:
# Podemos cerar un dataframe a partir de un diccionario de np.arrays o listas
np.random.seed(0)
pd.DataFrame({'random': np.random.rand(5),
             'text': ['hot','warm','cool','cold',None],
             'truth': [np.random.choice([True, False]) for _ in range(5)]
             },
            index=pd.date_range(end=datetime.date(2019, 4, 21), freq = '1D', periods=5, name='date')
            )

random  text  truth
date                             
2019-04-17  0.548814   hot  False
2019-04-18  0.715189  warm   True
2019-04-19  0.602763  cool   True
2019-04-20  0.544883  cold  False
2019-04-21  0.423655  None   True

In [33]:
# Podemos crear un dataframe a partir de una lista de diccionarios
pd.DataFrame([ {'mag' : 5.2, 'place' : 'California'},
              {'mag' : 1.2, 'place' : 'Alaska'}, 
              {'mag' : 0.2, 'place' : 'California'},
             ])


mag       place
0  5.2  California
1  1.2      Alaska
2  0.2  California

In [34]:
# Podemos crear un dataframe a partir de una lista de tuplas

list_of_tuples = [ (n, n**2, n**3) for n in range(5)]
pd.DataFrame(list_of_tuples, columns=["n", "n_squared", "n_cubed"])

n  n_squared  n_cubed
0  0          0        0
1  1          1        1
2  2          4        8
3  3          9       27
4  4         16       64

In [35]:
# Podemos crear un DataFrame desde un numpy array
pd.DataFrame(np.array([[0, 0, 0],[1, 1, 1], [2, 4, 8], [3, 9, 27], [4, 16, 64]]), 
             columns=['n', 'n_squared', 'n_cubed'] )


n  n_squared  n_cubed
0  0          0        0
1  1          1        1
2  2          4        8
3  3          9       27
4  4         16       64